version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ecosense_postgres
    restart: always
    environment:
      POSTGRES_DB: ecosense_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ITIC_BCN
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecosense_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: ecosense_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ecosense@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ecosense2025
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - ecosense_net

volumes:
  postgres_data:

networks:
  ecosense_net:
    driver: bridge
